config/routes.rb
Groverflow::Application.routes.draw do

  root :to => 'questions#index'
  match 'login' => 'sessions#new', :as => :login
  resources :users, :only => [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :questions, only: [:index, :new, :create, :show] do
    resources :votes, only: [:create, :update, :destroy] 
    resources :answers, only: [:create]
    resources :comments, only: [:create]

  end

  resources :answers, only: [] do
    resources :votes, only: [:create, :update, :destroy]
    resources :comments, only: [:create]
  end

end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  title      :string(255)      not null
#  content    :text             not null
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ActiveRecord::Base
  attr_accessible :title, :content

  validates :title, :content, presence: true
  belongs_to :user
  has_many :answers
  has_many :votes, as: :votable
  has_many :comments, as: :commentable
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  skip_before_filter :require_login, only: [:index, :show]

  def index
    # TODO-JW: consider pagination or something ...
    @questions = Question.all
  end  

  def new
    if logged_in?
      @question = Question.new
    else
      redirect_to root_path
    end
  end

  def create
    @question = current_user.questions.create(params[:question])
    if @question.errors.any?
      debugger
      flash.now[:errors] = "You had an error!"
      #@question = Question.new(params[:question])
      render :new
    else
      redirect_to question_path(@question)
    end
  end

  def show
    @question = Question.find(params[:id])
    @question.answers.new
    @question.comments.new
    @question_vote = @question.votes.find_by_user_id(current_user.id) if logged_in?
  end

end

app/views/questions/index.html.haml
.content
  .mainbar
    %h3 All Questions
  .questions
  -@questions.each do |question|
    .question-summary
      .stats
        .vote
          .vote-count-post
            %strong= question.votes.sum(:value)
          .viewcount
            votes
        .answer
          .answer-count-post
            %strong= question.answers.count
          .viewcount
            answers
      .summary
        %h3= link_to question.title, question_path(question)
        .post-time
          asked __ seconds ago
        .user-info
          .user-details
            = question.user.username
          .user-gravatar
            %img{src: "http://www.themillions.com/wp-content/uploads/2012/10/570_big-bird-wins.jpg", height: 30, width:30}          

app/views/questions/new.html.haml
- if flash[:errors]
  %p.errors
    = flash[:errors]

= form_for @question, {html: {id: "gen_form"} } do |f| 
  .form-title
    %h1 We're here to help!
    =image_tag "grover_side.png", height: 100
  %p
    = f.text_field :title, {class: "text", placeholder: "your question"}
    - if @question.errors[:title].any?
      %span.errors
        = @question.errors[:title].join(',')
  %p
    = f.text_area :content, {class: "textarea", placeholder: "some helpful details"}
    - if @question.errors[:content].any?
      %span.errors
        = @question.errors[:content].join(',')
  %p= f.submit 'Ask!', {class: "submit"}

app/views/questions/show.html.haml
.some_dealie
  .header

    -if @question_vote
      -vote_class = 'downvoted' if @question_vote.value == -1
      -vote_class = 'upvoted' if @question_vote.value == 1
    -else
      -vote_class = 'notvoted'
      
    -if current_user
      #question_votes{:class => "#{vote_class}"}
        =link_to image_tag('upvote_unselected.png'), question_votes_path(@question, vote_value: 1), remote:true, method: "post", class: "empty-state u-create"
        =link_to image_tag('upvote_unselected.png'), question_vote_path(@question, vote_value: 1), remote:true, method: "put", class: "downvote-state u-update"
        =link_to image_tag('upvote_selected.png'), question_vote_path(@question), remote:true, method: "delete", class: "upvote-state u-delete"
        %h2.vote_count=@question.votes.sum(:value)
        =link_to image_tag('downvote_unselected.png'), question_votes_path(@question, vote_value: -1), remote:true, method: "post", class: "empty-state d-create"
        =link_to image_tag('downvote_unselected.png'), question_vote_path(@question, vote_value: -1), remote:true, method: "put", class: "upvote-state d-update"
        =link_to image_tag('downvote_selected.png'), question_vote_path(@question), remote:true, method: "delete", class: "downvote-state d-delete"

    .question_header
      %h1.question_title
        =@question.title
      %h4.question_author
        =@question.user.username
      %p.question_content
        =@question.content


.responses
  .all_answers
    = render partial: "answers/form", locals: { question: @question, answer: @question.answers.last }
    - Answer.where(question_id: @question.id).each do |answer|
      .answer
        .answer_id{:id => "\#{answer.id}"}
        -if current_user
          -vote = answer.votes.find_by_user_id(current_user.id)
          -if vote
            -vote_class = 'downvoted' if vote.value == -1
            -vote_class = 'upvoted' if vote.value == 1
          -else
            -vote_class = 'notvoted'
          %div{:class => "answer_votes #{vote_class}"}
            =link_to image_tag('upvote_unselected.png'), answer_votes_path(answer, vote_value: 1), remote:true, method: "post", class: "empty-state u-create"
            =link_to image_tag('upvote_unselected.png'), answer_vote_path(answer, vote_value: 1), remote:true, method: "put", class: "downvote-state u-update"
            =link_to image_tag('upvote_selected.png'), answer_vote_path(answer), remote:true, method: "delete", class: "upvote-state u-delete"
            %h4.vote_count=answer.votes.sum(:value)
            =link_to image_tag('downvote_unselected.png'), answer_votes_path(answer, vote_value: -1), remote:true, method: "post", class: "empty-state d-create"
            =link_to image_tag('downvote_unselected.png'), answer_vote_path(answer, vote_value: -1), remote:true, method: "put", class: "upvote-state d-update"
            =link_to image_tag('downvote_selected.png'), answer_vote_path(answer), remote:true, method: "delete", class: "downvote-state d-delete"
        .answer_body
          = answer.content
          %h6= answer.user.username
        = render partial: "comments/answer_form", locals: { answer: answer, answer_comment: answer.comments.new }
        / %h6= User.find(answer.user_id).username
        .answer_comments
          - answer.comments.each do |comment|
            %p
              =comment.content
        
  .comments_box
    = render partial: "comments/question_form", locals: { question: @question, question_comment: @question.comments.last }
    .question_comments
      -if @question.comments.all.any?
        - @question.comments.all.each do |comment| 
          .comment 
            = comment.user.username + ": " + comment.content

          / = User.find(comment.user_id).username