config/routes.rb
Groverflow::Application.routes.draw do

  root :to => 'questions#index'
  match 'login' => 'sessions#new', :as => :login
  resources :users, :only => [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :questions, only: [:index, :new, :create, :show] do
    resources :votes, only: [:create, :update, :destroy] 
    resources :answers, only: [:create]
    resources :comments, only: [:create]

  end

  resources :answers, only: [] do
    resources :votes, only: [:create, :update, :destroy]
    resources :comments, only: [:create]
  end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Groverflow
    =stylesheet_link_tag    "application", :media => "all"
    =javascript_include_tag "application"
    =stylesheet_link_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/css/bootstrap.min.css"
    =javascript_include_tag "//netdna.bootstrapcdn.com/bootstrap/3.0.0-rc1/js/bootstrap.min.js"
    =csrf_meta_tags
  %body
    .container
      .top_bar
        =link_to image_tag("groverflow_logo_small.png", width: '200'), root_path
        %nav
          %ul
            -if logged_in?
              %li
                =link_to "Ask for dating advice", new_question_path
              %li
                =link_to "Logout", session_path(current_user), {method: :delete}
            -else
              %li
                =link_to "Signup", new_user_path
              %li
                =link_to "Sign In", new_session_path
    
      
      =yield